FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV CONSCIENCE_HOST=0.0.0.0
ENV CONSCIENCE_PORT=8080

COPY . /app

EXPOSE 8080

CMD ["python", "production_service.py"]
